# Generated by Django 5.2.7 on 2026-04-08 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_id", models.IntegerField()),
                ("template_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization__org_name", "template_id"],
                "unique_together": {("organization", "template_id")},
            },
        ),
    ]
