# Generated by Django 5.2.7 on 2026-02-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_language_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Consultant"), (2, "Lead")],
                default=2,
                null=True,
            ),
        ),
    ]
