# Generated by Django 5.2.7 on 2026-02-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.SmallIntegerField(
                choices=[(1, "Consultant"), (2, "Lead")], default=0
            ),
        ),
    ]
