# Generated by Django 5.2.7 on 2026-03-20 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CallCH",
            fields=[
                ("uuid", models.TextField(primary_key=True, serialize=False)),
                ("schema_name", models.TextField()),
                ("phone_number", models.TextField()),
                ("template_id", models.IntegerField()),
                ("duration", models.IntegerField(null=True)),
                ("language", models.TextField()),
                ("attempt_on_time_stamp", models.DateTimeField()),
            ],
            options={
                "db_table": "cai_call",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EvaluationMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("min_value", models.SmallIntegerField()),
                ("max_value", models.SmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.TextField(db_index=True, unique=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("lead_comment", models.TextField(blank=True, null=True)),
                ("rated_at", models.DateTimeField(blank=True, null=True)),
                ("consultant_comment", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Not Rated"),
                            (2, "Rated"),
                            (3, "Production Issue"),
                            (4, "Approved"),
                        ],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("rating_locked", models.BooleanField(default=False)),
                ("rating_locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt_on_time_stamp",
                    models.DateTimeField(db_index=True, null=True),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "rated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultant_rated_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="calls.tag")),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationCallRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.SmallIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="calls.call"
                    ),
                ),
                (
                    "rated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calls.evaluationmetric",
                    ),
                ),
            ],
            options={
                "unique_together": {("call", "parameter", "rated_by")},
            },
        ),
    ]
