# Generated by Django 5.2.7 on 2026-03-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
