# Generated by Django 5.2.7 on 2026-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallCH",
            fields=[
                ("uuid", models.TextField(primary_key=True, serialize=False)),
                ("schema_name", models.TextField()),
                ("phone_number", models.TextField()),
                ("template_id", models.IntegerField()),
                ("duration", models.IntegerField(null=True)),
                ("language", models.TextField()),
            ],
            options={
                "db_table": "cai_call",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="call",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="call",
            name="language",
        ),
        migrations.RemoveField(
            model_name="call",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="call",
            name="schema_name",
        ),
        migrations.RemoveField(
            model_name="call",
            name="template_id",
        ),
    ]
