# Generated by Django 5.2.7 on 2026-04-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
