# Generated by Django 5.2.7 on 2026-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0002_entitydefinition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitydefinition",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("boolean", "Boolean"),
                    ("time", "Time"),
                ],
                max_length=50,
            ),
        ),
    ]
