# Generated by Django 5.2.7 on 2026-03-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0002_call_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="call",
            name="created",
        ),
        migrations.AddField(
            model_name="call",
            name="attempt_on_time_stamp",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
