# Generated by Django 5.2.7 on 2026-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_remove_call_created_call_attempt_on_time_stamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="language",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="call",
            name="phone_number",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="call",
            name="schema_name",
            field=models.TextField(db_index=True),
        ),
    ]
