# Generated by Django 5.2.7 on 2026-04-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_alter_entitydefinition_data_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallTurnwiseCH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.TextField()),
                ("round", models.IntegerField()),
                ("stt_output", models.TextField(blank=True, null=True)),
                ("tts_input", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "cai_turnwise_call",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="call",
            name="good_audio_to_share",
            field=models.BooleanField(default=False),
        ),
    ]
