# Generated by Django 5.2.7 on 2026-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0004_callturnwisech_call_good_audio_to_share"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="good_audio_to_share",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
