# Generated by Django 5.2.7 on 2026-04-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0005_alter_call_good_audio_to_share"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="good_audio_to_share",
            field=models.BooleanField(default=False),
        ),
    ]
