version: "3.9"

services:
  # PostgreSQL
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network

  # ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "9000:9000"   # TCP client port
      - "8123:8123"   # HTTP port
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "password"   # or set your password
      CLICKHOUSE_DB: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
    - app-network
  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-dev
    restart: always
    command: ["./wait-for-db.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - db
      - clickhouse
    networks:
      - app-network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-dev
    restart: always
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin_data:
  clickhouse_data:

networks:
  app-network:
    driver: bridge